# Generated by Django 5.1.15 on 2026-02-21 17:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('source', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('MULTIMODAL', 'Multimodal')], default='TEXT', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('symptoms_text', models.TextField(blank=True, default='')),
                ('inference_mode', models.CharField(choices=[('CLIENT', 'Client-Side'), ('SERVER', 'Server-Side')], default='CLIENT', help_text='Whether inference ran on-device or server fallback.', max_length=20)),
                ('model_version', models.CharField(blank=True, default='', max_length=100)),
                ('device_info', models.JSONField(blank=True, default=dict, help_text='Client device capabilities (WebGPU, RAM, etc.)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TriageResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('diagnosis', models.TextField(help_text='Primary diagnosis or assessment summary.')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('confidence_score', models.FloatField(help_text='Model confidence 0.0 — 1.0')),
                ('recommendations', models.JSONField(default=list, help_text='List of recommended actions.')),
                ('differential_diagnoses', models.JSONField(default=list, help_text='Alternative diagnoses with confidence scores.')),
                ('explainability', models.JSONField(default=dict, help_text='XAI data: contributing factors, feature importance.')),
                ('raw_model_output', models.JSONField(blank=True, default=dict, help_text='Raw model response for debugging.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='triage.triagesession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('image', models.ImageField(upload_to='triage/images/%Y/%m/%d/')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('classification', models.CharField(blank=True, default='', help_text='Predicted classification label.', max_length=255)),
                ('classification_confidence', models.FloatField(blank=True, help_text='Vision model confidence 0.0 — 1.0', null=True)),
                ('vision_model_version', models.CharField(blank=True, default='', max_length=100)),
                ('analysis_metadata', models.JSONField(blank=True, default=dict, help_text='Additional vision analysis data.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='triage.triagesession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='triagesession',
            index=models.Index(fields=['user', '-created_at'], name='triage_tria_user_id_d27a9a_idx'),
        ),
        migrations.AddIndex(
            model_name='triagesession',
            index=models.Index(fields=['status'], name='triage_tria_status_d89c48_idx'),
        ),
    ]
