# Generated by Django 5.1.15 on 2026-02-21 21:42

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('record_type', models.CharField(choices=[('CONDITION', 'Condition / Diagnosis'), ('MEDICATION', 'Medication'), ('ALLERGY', 'Allergy'), ('PROCEDURE', 'Procedure'), ('VITAL', 'Vital Sign'), ('LAB_RESULT', 'Lab Result'), ('IMMUNIZATION', 'Immunization'), ('FAMILY_HISTORY', 'Family History'), ('OTHER', 'Other')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', encrypted_model_fields.fields.EncryptedTextField(blank=True, default='')),
                ('date_recorded', models.DateField(blank=True, help_text='When the condition was diagnosed or the event occurred.', null=True)),
                ('provider', models.CharField(blank=True, default='', help_text='Healthcare provider or facility name.', max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESOLVED', 'Resolved'), ('CHRONIC', 'Chronic')], default='ACTIVE', max_length=20)),
                ('severity', models.CharField(blank=True, choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe')], default='', max_length=20)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Flexible key-value data (dosage, frequency, values, etc.).')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_recorded', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('file', models.FileField(upload_to='records/documents/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('LAB_REPORT', 'Lab Report'), ('DISCHARGE_SUMMARY', 'Discharge Summary'), ('PRESCRIPTION', 'Prescription'), ('IMAGING', 'Imaging Report'), ('REFERRAL', 'Referral Letter'), ('INSURANCE', 'Insurance Document'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('extracted_text', encrypted_model_fields.fields.EncryptedTextField(blank=True, default='', help_text='Text extracted from the document for AI context.')),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_documents', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(blank=True, help_text='Optional link to a structured record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='records.medicalrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['user', 'record_type'], name='records_med_user_id_1251fa_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['user', '-created_at'], name='records_med_user_id_5f16d8_idx'),
        ),
    ]
